name: A workflow for building Nerves system
on: push

jobs:
  build:
    name:  Build Nerves system
    runs-on: ubuntu-latest
    container: nervesproject/nerves_system_br:1.18.5
    env:
      ELIXIR_VERSION: 1.12.3-otp-24
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache buildroot downloads
        id: cache-downloads
        uses: actions/cache@v2
        with:
          path: |
            ~/.nerves/dl
          key: buildroot-cache-${{ hashFiles('VERSION', 'mix.lock') }}
          restore-keys: |
            buildroot-cache-
            buidroot-dl-
      - name: Setup elixir
        run: |
          wget https://repo.hex.pm/builds/elixir/v$ELIXIR_VERSION.zip 
          unzip -d /usr/local/elixir v$ELIXIR_VERSION.zip
          echo "/usr/local/elixir/bin" >> $GITHUB_PATH
      - name: build
        run: |
          apt-get update
          apt-get install -y u-boot-tools
          mkdir -p /root/local
          mkdir -p /root/empty
          make dist
      - name: Clear Artifacts
        run: |
          rm -rf $HOME/.nerves/dl/ly11_system_rpi4-portable*
      - name: Upload S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-1'
          SOURCE_DIR: $HOME/.nerves/dl
      - name: Upload Artifacts
        if: contains(github.ref, 'tags')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          tag: ${{ github.ref }}
      - name: Upload Buildroot cache
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-1'
          SOURCE_DIR: $HOME/.nerves/dl 
        continue-on-error: true
